"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import {exo1} from './exo1';
var barre_1 = require("./barre");
var exo_algo_1_1 = require("./exo_algo_1");
var exo_algo_2_1 = require("./exo_algo_2");
var exo_algo_3_1 = require("./exo_algo_3");
var exo_3_1 = require("./exo_3");
(0, exo_algo_1_1.exo_algo_1)();
(0, barre_1.barre)();
(0, exo_algo_2_1.exo_algo_2)();
(0, barre_1.barre)();
(0, exo_algo_3_1.exo_algo_3)(800, 2);
(0, barre_1.barre)();
(0, exo_algo_3_1.exo_algo_3)(20, 2);
(0, barre_1.barre)();
(0, exo_algo_3_1.exo_algo_3)(800, 5);
(0, barre_1.barre)();
(0, exo_3_1.exo_3)();
